# Generated by Django 5.0.6 on 2024-05-21 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_a', models.CharField(max_length=3)),
                ('currency_b', models.CharField(max_length=3)),
                ('latest_rate_sell', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('latest_rate_buy', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('latest_rate_cross', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['currency_a'],
                'unique_together': {('currency_a', 'currency_b')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('rate_buy', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rate_sell', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rate_cross', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='currencies.currency')),
            ],
            options={
                'verbose_name': 'Currency_History',
                'verbose_name_plural': 'Currencies_Histories',
                'ordering': ['datetime'],
                'unique_together': {('currency', 'datetime')},
            },
        ),
    ]
